name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # أو master حسب اسم الفرع الرئيسي عندك

# إعطاء الصلاحيات اللازمة للرفع على GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# إلغاء العمليات السابقة المعلقة إذا رفعت تحديث جديد بسرعة
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # يرفع المجلد الرئيسي كامل، إذا ملفاتك داخل مجلد معين (مثل public) غير الـ "." إلى اسم المجلد
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5  # نسخة مستقرة ومحدثة لحل مشكلة الفشل المؤقت
